import XCTest
@testable import ParfastCore

/// Phase 1: the REAL engine, over the acceptance corpus from plan section 7.
///
/// These are the tests that say the app does what it claims. Everything else
/// in this suite grades the app against the mock, which is a scripted picture
/// of what the engine does; this one grades it against the engine.
///
/// The corpus is generated by `apps/parfast/shared/corpus/make-corpus.py`
/// (chip D) and its expected verdicts are MEASURED out of `parfast v`, not
/// typed - so a disagreement here is a real disagreement between this app and
/// the CLI, which is the only comparison worth making.
///
/// TWO gates stand between a checkout and these tests, and they fail in
/// different ways. The STATICLIB decides whether they are COMPILED at all -
/// `Package.swift` defines `PARFAST_FFI` only when
/// `mac/vendor/lib/libparfast_ffi.a` exists - and `PARFAST_CORPUS` decides
/// whether the compiled ones RUN.
///
/// Without the corpus they skip rather than fail: a box with no corpus is not
/// a broken app, and a green suite that silently ran nothing is the rubber
/// stamp this repo's gate list exists to refuse - so the skip SAYS so.
///
/// Without the staticlib they used to say NOTHING, because a compiled-out
/// test cannot announce itself: the suite simply reported a smaller green
/// total. `testTheRealEngineTestsAreCompiledIn` below is outside the
/// conditional so that case speaks too.
final class FfiCoreTests: XCTestCase {

    private var corpus: URL? {
        guard let path = ProcessInfo.processInfo.environment["PARFAST_CORPUS"],
              FileManager.default.fileExists(atPath: path) else { return nil }
        return URL(fileURLWithPath: path)
    }

    /// Every caller of this lives inside the `#if PARFAST_FFI` below, so
    /// there is no staticlib-less arm to write here. One WAS written - this
    /// function opened with `#if !PARFAST_FFI throw XCTSkip("built without
    /// the staticlib; MockCore only")` until 12 Sep 2026 - and it was
    /// unreachable for exactly that reason, which is why a build with no
    /// staticlib was silent rather than skipping out loud. That intent now
    /// lives in the test below, which is compiled unconditionally so it can
    /// actually run.
    private func requireCorpus() throws -> URL {
        guard let corpus else {
            throw XCTSkip("set PARFAST_CORPUS to a make-corpus.py output directory")
        }
        return corpus
    }

    /// The one test in this file OUTSIDE `#if PARFAST_FFI`, and the only
    /// thing that makes a staticlib-less build SAY so.
    ///
    /// A test that is compiled out cannot report its own absence, so the
    /// suite just prints a smaller total and a clean green - and the totals
    /// are close enough to read past. Measured on 12 Sep 2026: 84 tests with
    /// no staticlib, 98 with one (14 of those skipping for want of a
    /// corpus). Nothing in the 84 run mentioned the 14, and a lane chasing
    /// the difference had a staticlib on disk the whole time - SwiftPM had
    /// cached the manifest evaluation from before it was built, so
    /// `Package.swift`'s file check had answered no and the define stayed
    /// off. Same number, opposite cause, and no output told them apart.
    ///
    /// A SKIP carries its reason into the run's own output. That is the
    /// whole point of this test: it turns "a lane has to remember" into
    /// something the suite says by itself.
    ///
    /// # The remedy below used to be wrong, which cost the next lane the same hour
    ///
    /// It said "touch Package.swift or clear .build", and on 12 Sep 2026 a lane did
    /// BOTH - with the staticlib on disk - and still got the skip. SwiftPM's manifest
    /// cache is not in `.build`: it is per-user and outlives both, so
    /// `--manifest-cache none` (or `swift package purge-cache`) is the thing that
    /// actually re-evaluates the file check.
    ///
    /// AND IT IS WORSE THAN STALE, it is NONDETERMINISTIC. Measured the same day, with
    /// the staticlib in place for the whole sequence: a `swift test --list-tests` listed
    /// all fifteen cases in this file and the plain `swift test` beside it ran 138, then
    /// a later plain run ran 153. The cache is keyed on the manifest and not on the
    /// filesystem state the manifest INSPECTS, so consecutive commands can disagree.
    /// The consequence for anything automated: never assert "the real-engine tests
    /// compiled in" from a different invocation than the one whose result you are
    /// trusting. `parfast-gui`'s mac job greps THIS test's skip out of the same
    /// `swift test` output for exactly that reason. `swift build --verbose` made it look
    /// settled the other way, because the compile line it prints for the APP targets
    /// carries `-D PARFAST_FFI` while the cached manifest keeps it off the test
    /// target - so the one check that looked decisive was the misleading one. The
    /// deciding command is `swift test --list-tests`, which names what is compiled in.
    func testTheRealEngineTestsAreCompiledIn() throws {
        #if !PARFAST_FFI
        throw XCTSkip("""
            built without the staticlib: MockCore only. The real-engine \
            tests in this file are COMPILED OUT, so this run is 14 tests \
            smaller than a full one and nothing else here will say so. \
            Build mac/vendor/lib/libparfast_ffi.a (mac/make-app.sh, or the \
            cargo line it runs) to compile them in. If you have one on disk \
            already and still see this, SwiftPM has cached the manifest \
            evaluation from before it existed - and clearing .build does NOT \
            clear that cache, because it is per-user and not per-build-dir. \
            Re-run as `swift test --manifest-cache none`, or \
            `swift package purge-cache` once. `swift test --list-tests` is \
            the check that answers whether they are compiled in; a \
            `swift build --verbose` line showing -D PARFAST_FFI is NOT, \
            because it is the app target's and not this one's. Then point \
            PARFAST_CORPUS at a make-corpus.py output directory to run the \
            corpus tests; PlannerParityTests needs only the staticlib.
            """)
        #endif
    }

    #if PARFAST_FFI

    /// What the generator MEASURED, read from its own `expected.json`. The
    /// field MEANINGS are the generator's, and the first cut of this test
    /// guessed at them and mapped `available_blocks` onto the wrong quantity,
    /// so each one is spelled out:
    ///
    /// - `available_blocks` - SOURCE blocks present on disk (80 of 80 clean).
    /// - `recovery_blocks`  - RECOVERY blocks available; null when none.
    /// - `blocks_owed`      - source blocks a repair would have to rebuild.
    /// - `blocks_short`     - how many more recovery blocks would be needed.
    private struct Expected: Decodable {
        struct SetInfo: Decodable {
            let dir: String
            let par2: String
        }
        struct CLI: Decodable {
            let verify_exit: Int
            let block_size: Int64
            let source_blocks: Int
            let available_blocks: Int
            let recovery_blocks: Int?
            let blocks_owed: Int
            let blocks_short: Int
            let files_ok: Int
            let files_damaged: Int
            let files_missing: Int
            let verdict: String
        }
        /// What the two apps are GRADED on, in the generator's own words.
        struct UI: Decodable {
            let verdict: String
            let block_states_present: [String]
            let repair_button: String
        }
        let scenario: String
        let set: SetInfo
        let cli: CLI
        let ui: UI
    }

    private func expected(_ name: String, in corpus: URL) throws -> Expected {
        let url = corpus.appendingPathComponent(name).appendingPathComponent("expected.json")
        return try JSONDecoder().decode(Expected.self, from: Data(contentsOf: url))
    }

    /// The index .par2 from the generator's own record of where it put it,
    /// never by guessing at a directory listing.
    private func par2(_ name: String, in corpus: URL) throws -> String {
        let want = try expected(name, in: corpus)
        let path = corpus.appendingPathComponent(name)
            .appendingPathComponent(want.set.dir)
            .appendingPathComponent(want.set.par2)
        XCTAssertTrue(FileManager.default.fileExists(atPath: path.path),
                      "\(name): expected.json points at \(path.path) and nothing is there")
        return path.path
    }

    /// The nine PAR2 scenarios. `checksums` is the tenth and carries no
    /// `.par2` at all - `set.par2` is null in its record - so it has its own
    /// test rather than being bent into this loop.
    private static let scenarios = ["clean", "damaged", "missing", "misnamed", "moved",
                                    "unrepairable", "unicode", "blocks10k", "volgaps"]

    private func run(_ core: FfiCore, _ spec: JobSpec,
                     timeout: TimeInterval = 120) throws -> JobSnapshot {
        let id = try core.submit(spec)
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            let snapshot = try core.snapshot(job: id)
            if snapshot.state.isFinished { return snapshot }
            RunLoop.current.run(until: Date().addingTimeInterval(0.02))
        }
        XCTFail("job \(id) did not finish inside \(timeout)s")
        return try core.snapshot(job: id)
    }

    // MARK: - The corpus

    func testEveryCorpusScenarioGetsTheVerdictTheCLIMeasured() throws {
        let corpus = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        var checked = 0
        for name in Self.scenarios {
            let want = try expected(name, in: corpus)
            let snapshot = try run(core, .verify(VerifySpec(par2: try par2(name, in: corpus))))
            XCTAssertEqual(snapshot.state, .done, "\(name): \(snapshot.error?.message ?? "")")
            let survey = try XCTUnwrap(snapshot.survey, name)

            XCTAssertEqual(survey.verdict.rawValue, want.cli.verdict, "\(name): verdict")
            XCTAssertEqual(survey.block_size, want.cli.block_size, "\(name): block size")
            XCTAssertEqual(survey.source_blocks, want.cli.source_blocks, "\(name): source blocks")
            XCTAssertEqual(survey.recovery_needed, want.cli.blocks_owed, "\(name): blocks owed")
            if let recovery = want.cli.recovery_blocks {
                XCTAssertEqual(survey.recovery_available, recovery, "\(name): recovery blocks")
            }

            // The block map must describe the SAME set the header does, and
            // hold the states the generator says the picture has to show.
            let states = survey.expandedStates()
            XCTAssertEqual(states.count, survey.source_blocks, "\(name): map length")
            let drawn = Set(states.map(\.corpusName))
            XCTAssertEqual(drawn, Set(want.ui.block_states_present),
                           "\(name): map draws \(drawn.sorted()), corpus expects \(want.ui.block_states_present.sorted())")

            // `cli.files_missing` is deliberately NOT graded. It is the
            // REFERENCE TOOL's vocabulary: par2cmdline calls a renamed member
            // missing because its name is not in the directory, while the
            // survey calls it misnamed and says where it was found. Both
            // describe the same disk and both spend the same recovery blocks,
            // which is why the verdict and blocks_owed agree. The app is
            // graded against the `ui` block; chip D's scenario note says so at
            // the site.
            XCTAssertEqual(survey.files.filter { $0.status == .damaged }.count,
                           want.cli.files_damaged, "\(name): files damaged")
            checked += 1
        }
        // Failing to find is failing: a loop that ran zero times passes every
        // assertion inside it.
        XCTAssertEqual(checked, Self.scenarios.count)
    }

    /// The Repair button, graded against the generator's own `ui.repair_button`
    /// rather than eyeballed: "an enabled button that fails on press is worse
    /// than a disabled one" is the corpus's note, and it is right.
    func testTheRepairButtonIsOfferedExactlyWhenTheCorpusSaysSo() throws {
        let corpus = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        for name in Self.scenarios {
            let want = try expected(name, in: corpus)
            let snapshot = try run(core, .verify(VerifySpec(par2: try par2(name, in: corpus))))
            let survey = try XCTUnwrap(snapshot.survey, name)
            // VerifyModel.canRepair's predicate, on the real survey. The
            // misnamed arm is what keeps this GREEN on the scenario the core
            // currently mis-verdicts: the app offers the repair the CLI says
            // is possible, off the survey's own file rows.
            let offered = survey.verdict == .repairable
            XCTAssertEqual(offered, want.ui.repair_button == "enabled",
                           "\(name): corpus says repair_button is \(want.ui.repair_button)")
        }
    }

    /// The CLI's exit code is the one thing a script user already knows, so a
    /// disagreement with it is a disagreement the GUI cannot explain away.
    func testTheExitCodeAgreesWithTheCLI() throws {
        let corpus = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        for name in ["clean", "damaged", "unrepairable"] {
            let want = try expected(name, in: corpus)
            let snapshot = try run(core, .verify(VerifySpec(par2: try par2(name, in: corpus))))
            XCTAssertEqual(snapshot.result?.exit_code, want.cli.verify_exit, name)
        }
    }

    /// `misnamed` was a CORE DEFECT between 12 Sep 06:20Z and its fix that
    /// morning: the snapshot carried `exit_code: 1` and `verdict: "complete"`
    /// in one object, and the window showed a green "no repair needed" over a
    /// set the CLI could repair. This is what is left of it - the scenario
    /// behaves like the other eight now, and this asserts the two halves
    /// agree, because that is the invariant that broke.
    func testMisnamedAgreesWithItsOwnExitCode() throws {
        let corpus = try requireCorpus()
        let want = try expected("misnamed", in: corpus)
        let core = try XCTUnwrap(FfiCore())
        let snapshot = try run(core, .verify(VerifySpec(par2: try par2("misnamed", in: corpus))))
        let survey = try XCTUnwrap(snapshot.survey)

        XCTAssertEqual(survey.verdict.rawValue, want.cli.verdict)
        XCTAssertEqual(snapshot.result?.exit_code, want.cli.verify_exit)
        XCTAssertEqual(survey.recovery_needed, want.cli.blocks_owed)
        // A complete verdict beside a non-zero exit code is the shape that
        // broke; it must never come back.
        if survey.verdict == .complete {
            XCTAssertEqual(snapshot.result?.exit_code, 0,
                           "complete and a non-zero exit code cannot both be true")
        }
        XCTAssertEqual(survey.misnamedFiles.count, 1)
        XCTAssertEqual(survey.misnamedFiles.first?.found_as?.hasSuffix("IMG_4417.dat"), true)
    }

    /// A repair on a COPY, so the corpus is not consumed by its own test.
    func testRepairingADamagedSetMakesItComplete() throws {
        let corpus = try requireCorpus()
        let want = try expected("damaged", in: corpus)
        let scratch = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("parfast-repair-\(UUID().uuidString)")
        try FileManager.default.copyItem(
            at: corpus.appendingPathComponent("damaged").appendingPathComponent(want.set.dir),
            to: scratch)
        defer { try? FileManager.default.removeItem(at: scratch) }
        let par2 = scratch.appendingPathComponent(want.set.par2).path

        let core = try XCTUnwrap(FfiCore())
        let repair = try run(core, .repairSet(RepairSpec(par2: par2)))
        XCTAssertEqual(repair.state, .done, repair.error?.message ?? "")
        XCTAssertGreaterThan(repair.result?.repaired_files ?? 0, 0)

        // And the set verifies clean afterwards, which is the claim that
        // matters. A repair that reports success and leaves a damaged set is
        // the failure this assertion exists for.
        let after = try run(core, .verify(VerifySpec(par2: par2)))
        XCTAssertEqual(after.survey?.verdict, .complete)
        XCTAssertEqual(after.result?.exit_code, 0)
    }

    /// Create, then verify what was created: the preview's promise against
    /// what reached the disk.
    func testCreatingASetWritesWhatThePreviewPromised() throws {
        _ = try requireCorpus()
        let scratch = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("parfast-create-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: scratch, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: scratch) }

        var sources: [SourceItem] = []
        for i in 1...3 {
            let file = scratch.appendingPathComponent(String(format: "part%02d.bin", i))
            var bytes = Data(count: 0)
            bytes.reserveCapacity(2_000_000)
            for b in 0..<2_000_000 { bytes.append(UInt8((b &* 31 &+ i) & 0xFF)) }
            try bytes.write(to: file)
            sources.append(SourceItem(path: file.path))
        }
        let output = scratch.appendingPathComponent("set.par2").path
        let spec = CreateSpec(sources: sources, block: .count(200),
                              recovery: .percent(10), output: output, volumes: .pow2)

        let core = try XCTUnwrap(FfiCore())
        let preview = try core.planPreview(spec)
        XCTAssertGreaterThan(preview.recovery_blocks, 0)
        XCTAssertFalse(preview.command.isEmpty)

        let created = try run(core, .create(spec))
        XCTAssertEqual(created.state, .done, created.error?.message ?? "")
        let written = try XCTUnwrap(created.result?.written)
        XCTAssertFalse(written.isEmpty)
        for file in written {
            XCTAssertTrue(
                FileManager.default.fileExists(
                    atPath: scratch.appendingPathComponent(file.name).path),
                "\(file.name) was reported written and is not there")
        }

        // The set it just made must verify clean.
        let verified = try run(core, .verify(VerifySpec(par2: output)))
        XCTAssertEqual(verified.survey?.verdict, .complete)
    }

    /// An SFV written by the engine and read back by it.
    func testChecksumRoundTrip() throws {
        _ = try requireCorpus()
        let scratch = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("parfast-sfv-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: scratch, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: scratch) }

        var sources: [SourceItem] = []
        for i in 1...4 {
            let file = scratch.appendingPathComponent("f\(i).bin")
            try Data(repeating: UInt8(i), count: 40_000).write(to: file)
            sources.append(SourceItem(path: file.path))
        }
        let list = scratch.appendingPathComponent("set.sfv").path
        let core = try XCTUnwrap(FfiCore())

        let made = try run(core, .checksumCreate(
            ChecksumCreateSpec(sources: sources, format: .sfv, output: list)))
        XCTAssertEqual(made.state, .done, made.error?.message ?? "")

        let checked = try run(core, .checksumVerify(ChecksumVerifySpec(file: list)))
        let result = try XCTUnwrap(checked.result?.checksum)
        XCTAssertEqual(result.ok, 4)
        XCTAssertEqual(result.mismatch, 0)
        XCTAssertEqual(result.missing, 0)
    }

    /// Three jobs, in order, one at a time - plan 5.5 and the chip's own
    /// done-means list.
    func testThreeQueuedJobsRunInOrder() throws {
        let corpus = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        var ids: [Int64] = []
        for name in ["clean", "damaged", "unicode"] {
            ids.append(try core.submit(.verify(VerifySpec(par2: try par2(name, in: corpus)))))
        }
        let deadline = Date().addingTimeInterval(120)
        var sawMoreThanOneRunning = false
        while Date() < deadline {
            let q = try core.queueSnapshot()
            if q.running > 1 { sawMoreThanOneRunning = true }
            if q.jobs.allSatisfy({ $0.state.isFinished }) { break }
            RunLoop.current.run(until: Date().addingTimeInterval(0.02))
        }
        let finished = try core.queueSnapshot()
        XCTAssertFalse(sawMoreThanOneRunning, "concurrency 1 must mean one at a time")
        XCTAssertEqual(finished.jobs.map(\.id), ids, "jobs are listed in submission order")
        XCTAssertTrue(finished.jobs.allSatisfy { $0.state == .done })
    }

    /// The capability table is what gates the controls, so it has to arrive.
    func testCapabilitiesArriveAndGateWhatTheyClaim() throws {
        _ = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        let caps = try core.capabilities()
        XCTAssertFalse(caps.version.isEmpty)
        XCTAssertFalse(caps.engine.isEmpty)
        // Not assertions about the VALUES - those are the core's to change -
        // but the fields must decode, because a missing one silently reads as
        // false and hides a control that works.
        _ = (caps.comment, caps.volume_limit_explicit, caps.cancel_in_fold,
             caps.pause_in_fold, caps.progress_in_fold)
    }

    func testSettingsRoundTripThroughTheCore() throws {
        _ = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        var settings = try core.settingsGet()
        let wanted = !settings.general.notifications
        settings.general.notifications = wanted
        settings.create.block_count = 4321
        try core.settingsSet(settings)
        let back = try core.settingsGet()
        XCTAssertEqual(back.general.notifications, wanted)
        XCTAssertEqual(back.create.block_count, 4321)
    }

    #endif
}


#if PARFAST_FFI
extension BlockState {
    /// The generator's spelling of each state in `ui.block_states_present`.
    /// One mapping, in one place, so a rename on either side fails loudly.
    var corpusName: String {
        switch self {
        case .pending: return "pending"
        case .present: return "present"
        case .damaged: return "damaged"
        case .missing: return "missing"
        case .misnamed: return "misnamed"
        case .hashing: return "hashing"
        }
    }
}
#endif


#if PARFAST_FFI
/// The app's OWN responsibility, separated from the corpus grading above:
/// whatever the core and the corpus settle on for a renamed member, the
/// window must draw what the survey says and nothing else.
extension FfiCoreTests {

    func testTheMapDrawsExactlyWhatTheSurveySays() throws {
        let corpus = try requireCorpus()
        let core = try XCTUnwrap(FfiCore())
        for name in Self.scenarios {
            let snapshot = try run(core, .verify(VerifySpec(par2: try par2(name, in: corpus))))
            let survey = try XCTUnwrap(snapshot.survey, name)
            let states = survey.expandedStates()

            // Length, and the per-state census, straight off block_runs.
            XCTAssertEqual(states.count, survey.source_blocks, name)
            var counted: [BlockState: Int] = [:]
            for s in states { counted[s, default: 0] += 1 }
            XCTAssertEqual(counted, survey.counts().filter { $0.value > 0 }, "\(name): RLE round trip")

            // A file the survey calls misnamed carries where it was found, and
            // its blocks are drawn misnamed rather than as damage.
            for file in survey.misnamedFiles {
                XCTAssertNotNil(file.found_as, "\(name): \(file.name) is misnamed with no found_as")
            }
            if !survey.misnamedFiles.isEmpty {
                XCTAssertGreaterThan(counted[.misnamed] ?? 0, 0, name)
            }
        }
    }
}
#endif


#if PARFAST_FFI
/// The `checksums` scenario, and the CROSS-CHECK chip D asked for.
///
/// Every other corpus scenario reads its verdict back out of `parfast v`.
/// This one cannot: parfast is a par2cmdline drop-in with no SFV mode, so
/// there is no reference run, and its expectations are DERIVED - a CRC32
/// computed from the bytes by the algorithm an SFV file is defined in terms
/// of, plus a status that follows from whether those bytes were then changed
/// or deleted. Chip D said so in the builder's docstring rather than burying
/// it, and named the gap: nothing had re-computed those numbers with a second
/// implementation.
///
/// `parfast-session`'s own checksum verify is that second implementation, and
/// this lane can reach it through the FFI. So these tests close the corpus's
/// own rule for its tenth scenario: if the engine independently arrives at
/// the same four rows, the derivation is confirmed rather than trusted.
extension FfiCoreTests {

    private struct ChecksumExpected: Decodable {
        struct SetInfo: Decodable {
            let dir: String
            let checksum_file: String
        }
        struct Row: Decodable {
            let name: String
            let expected: String
            let actual: String
            let status: String
        }
        struct Counts: Decodable {
            let ok: Int
            let mismatch: Int
            let missing: Int
        }
        struct Checksum: Decodable {
            let format: String
            let counts: Counts
            let entries: [Row]
        }
        struct UI: Decodable {
            let repair_button: String
            let checksum: Checksum
        }
        let set: SetInfo
        let ui: UI
    }

    private func checksumExpected(in corpus: URL) throws -> ChecksumExpected {
        let url = corpus.appendingPathComponent("checksums/expected.json")
        return try JSONDecoder().decode(ChecksumExpected.self, from: Data(contentsOf: url))
    }

    func testTheChecksumScenarioMatchesTheEngineRowForRow() throws {
        let corpus = try requireCorpus()
        let want = try checksumExpected(in: corpus)
        let file = corpus.appendingPathComponent("checksums")
            .appendingPathComponent(want.set.dir)
            .appendingPathComponent(want.set.checksum_file)
        XCTAssertTrue(FileManager.default.fileExists(atPath: file.path), file.path)

        let core = try XCTUnwrap(FfiCore())
        let snapshot = try run(core, .checksumVerify(ChecksumVerifySpec(file: file.path)))

        // A checksum verify that finds problems FAILS, with code
        // `checksum_mismatch` - the job's outcome is negative, the way a
        // non-zero exit code is. It is not `done`, which is what this test
        // assumed first.
        //
        // AND IT STILL CARRIES ITS FULL RESULT. That is the part worth
        // pinning: a host that reads `result` only on `.done` would show an
        // empty Checksums table on exactly the file the user opened it for.
        XCTAssertEqual(snapshot.state, .failed)
        XCTAssertEqual(snapshot.error?.code, "checksum_mismatch")
        let result = try XCTUnwrap(snapshot.result?.checksum,
                                   "a failed checksum verify must still carry its rows")

        XCTAssertEqual(result.ok, want.ui.checksum.counts.ok)
        XCTAssertEqual(result.mismatch, want.ui.checksum.counts.mismatch)
        XCTAssertEqual(result.missing, want.ui.checksum.counts.missing)

        // The rows, in the file's own order, field for field. This is the
        // cross-check: chip D derived these digests from the bytes, and the
        // engine computed them from the same bytes with different code.
        let rows = try XCTUnwrap(result.entries)
        XCTAssertEqual(rows.count, want.ui.checksum.entries.count,
                       "four rows, not zero - an empty table reads as a clean checksum file")
        for (got, wanted) in zip(rows, want.ui.checksum.entries) {
            XCTAssertEqual(got.name, wanted.name)
            XCTAssertEqual(got.expected.uppercased(), wanted.expected.uppercased(),
                           "\(wanted.name): expected digest")
            XCTAssertEqual(got.actual.uppercased(), wanted.actual.uppercased(),
                           "\(wanted.name): actual digest")
            XCTAssertEqual(got.status.rawValue, wanted.status, "\(wanted.name): status")
        }
    }

    /// The row an app is most likely to render as the word "null" (chip D's
    /// note): a missing file has no `actual` at all.
    func testTheMissingRowCarriesNoActualDigest() throws {
        let corpus = try requireCorpus()
        let want = try checksumExpected(in: corpus)
        let file = corpus.appendingPathComponent("checksums")
            .appendingPathComponent(want.set.dir)
            .appendingPathComponent(want.set.checksum_file)
        let core = try XCTUnwrap(FfiCore())
        let snapshot = try run(core, .checksumVerify(ChecksumVerifySpec(file: file.path)))
        let rows = try XCTUnwrap(snapshot.result?.checksum?.entries)

        let absent = try XCTUnwrap(rows.first { $0.status == .missing })
        XCTAssertTrue(absent.actual.isEmpty, "a missing file came to nothing, not to \"null\"")
        let mismatched = try XCTUnwrap(rows.first { $0.status == .mismatch })
        XCTAssertFalse(mismatched.actual.isEmpty, "a mismatch has two digests to show")
        XCTAssertNotEqual(mismatched.actual, mismatched.expected)
    }

    /// There is no block map and no Repair on this screen. An app offering a
    /// repair over a checksum file is reporting something it cannot do - a
    /// checksum says whether a file changed and cannot rebuild anything.
    func testTheChecksumScreenOffersNoRepair() throws {
        let corpus = try requireCorpus()
        let want = try checksumExpected(in: corpus)
        XCTAssertEqual(want.ui.repair_button, "absent")
        let file = corpus.appendingPathComponent("checksums")
            .appendingPathComponent(want.set.dir)
            .appendingPathComponent(want.set.checksum_file)
        let core = try XCTUnwrap(FfiCore())
        let snapshot = try run(core, .checksumVerify(ChecksumVerifySpec(file: file.path)))
        // No survey means no block map and nothing for VerifyModel.canRepair
        // to say yes to; the Checksums screen has no Repair control at all.
        XCTAssertNil(snapshot.survey)
    }
}
#endif
