//! The round-trip oracle: every posting-layout profile in
//! `crates/postfast/catalog/`, generated by `postfast`, served by the
//! mock, downloaded by the real `nzbfast` binary, and graded against
//! the end state the profile declares.
//!
//! **THIS FILE HOLDS NO CASES AND MUST NOT GROW ONE.** The tests are
//! written by `crates/nzbfast/build.rs` into `$OUT_DIR/layouts_gen.rs`,
//! one `#[tokio::test]` per profile, each a one-line call into
//! [`runner::run`]. A new row is a new `.toml` in the catalog and
//! nothing else - no edit here, no edit in the runner, no list of names
//! anywhere to forget. That is the point of the generated shape (spec
//! section 9.2, `research/SPEC-POSTING-LAYOUT-TOOLKIT-2026-09-03.md`):
//! a loop over the catalog inside one test would give one test NAME, so
//! a failure would say "layouts failed" instead of naming the row, and
//! the file would accumulate a case table until it met a size-gate
//! ceiling.
//!
//! WHY A MODULE HERE AND NOT ITS OWN `tests/layouts.rs` TARGET, which
//! is what spec section 9.1 asks for.
//!
//! ref-gate: `tests/layouts.rs` is deliberately NOT a file - it is the
//! target this module exists INSTEAD of, named so a reader coming from
//! the spec finds the answer here rather than concluding chip 04 was
//! never built. If it ever becomes a file again, the reason below is
//! what has to have changed.
//!
//! A separate `[[test]]` target is a
//! separate executable that statically links the whole crate graph on
//! every push, and `tools/test-target-gate.py` refuses a new one
//! outright unless it is heavy-gated (which would take these rows OUT
//! of the per-push run the spec wants them in) or has a process-wide
//! reason to own a binary. This has none: nextest gives every test its
//! own PROCESS whatever binary it lives in, so the fold costs the
//! oracle nothing and saves a link. Every property section 9 asks for
//! survives it - one test named after each profile, a single row
//! selectable with `-E 'test(layout_n2_opaque_c0_p0)'`, and the whole
//! directory running on push. Only the command spelling changes:
//!
//!     cargo nextest run -p nzbfast --test integration -E 'test(/^layouts::/)'
//!
//! WHY IT IS NOT `heavy-tests`-GATED. The profiles are deliberately
//! small - the catalog README asks every row to justify its payload -
//! so a layout regression is caught on the commit that lands it rather
//! than by a nightly. Spec section 9.1 budgets 90 s for the whole
//! directory on a loaded box; measured 3 Sep 2026 at 1.6 s idle and
//! 2.0-2.2 s under an 18-way spin load on an 18-core box, for the two
//! profiles the catalog held that day. A catalog that outgrows the
//! budget moves to a target of its own with `required-features =
//! ["heavy-tests"]`, which is the ONE thing that decision costs and the
//! one shape test-target-gate already allows.

// The runner lives beside this file, in `layouts/`, by the ordinary
// module-directory rule - no `#[path]` needed and none wanted.
mod runner;

// One `#[tokio::test]` per catalog profile. See the module header, and
// `emit_layout_tests` in `crates/nzbfast/build.rs`.
include!(concat!(env!("OUT_DIR"), "/layouts_gen.rs"));
