//! `[companion]`, plane 7.J: the metadata sidecar posted beside the
//! payload.
//!
//! An `.sfv` maps real names to CRC32s. It protects nothing and cannot
//! repair a byte, so it is not a recovery set - what it carries is the
//! half of a PAR2 set an obfuscated post actually depends on, the
//! NAMES, for a few hundred bytes against even a manifest-only set's
//! kilobytes. That is why the field ships it, and why a post can be
//! fully obfuscated with no PAR2 anywhere and still be recoverable by
//! name (`bench/capability-corpus` legs n21 and n34).
//!
//! **The sidecar is posted under its own name, whatever the naming
//! plane says, and that is a rule rather than a simplification.** The
//! payload rides under tokens precisely because the sidecar is the one
//! file that says what everything is; a token-named sidecar is a name
//! source nothing can find, and a row built on one would prove nothing
//! it claimed to. The client's own tier reads sidecars BY CONTENT as
//! well as by extension (`nzbfast_engine::get::sfvname`'s header, M4-20)
//! so an obfuscated sidecar is a real field shape - but it is a
//! different row, and it needs a naming key of its own before a profile
//! may claim it.
//!
//! **It names the RELATIVE path**, directories and all, which is what
//! makes an `.sfv` a tree carrier as well as a name carrier. The client
//! puts a sidecar name through the same member-name policy a PAR2
//! FileDesc path goes through, so the tree it spells is the tree that
//! lands.
//!
//! **Draw order: this stage draws nothing.** The sidecar's content is a
//! function of the payload and its own name, so adding `[companion]` to
//! a profile moves no payload name and no message-id.

use crate::assemble::SourceFile;
use crate::profile::Profile;

/// The sidecar a profile asked for: a file name and its bytes, fed back
/// into the ordinary pipeline as a posted file like any other.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompanionFile {
    pub name: String,
    pub bytes: Vec<u8>,
    /// The relative paths this sidecar NAMES, in the order it lists
    /// them.
    ///
    /// Carried rather than re-parsed out of `bytes`, because it is what
    /// the expectation is derived from: a member the sidecar names is a
    /// member whose real name the post carries, so it lands under that
    /// name instead of under its wire token. A stage that re-read the
    /// text would be a second implementation of the rule, and the two
    /// could disagree in exactly the direction that makes a row pass.
    pub names: Vec<String>,
}

/// Build the companion plane for one profile.
///
/// `posted` is the payload as it reaches the wire - the files a client
/// will actually have to name. A member that is described and never
/// posted (a P5 placeholder, a G5 dedupe copy) is deliberately NOT
/// listed: a sidecar entry for a file no article carries is a checksum
/// nothing can be matched against, and the tier that reads it would
/// decline the line rather than invent the file.
pub fn build(profile: &Profile, posted: &[SourceFile]) -> Option<CompanionFile> {
    if !profile.companion.sfv {
        return None;
    }
    let mut text = String::from("; generated by postfast, one line per posted file\n");
    let mut names = Vec::with_capacity(posted.len());
    for f in posted {
        let mut h = crc32fast::Hasher::new();
        h.update(&f.bytes);
        names.push(f.rel.clone());
        // The canonical SFV spelling: the name, a single space, and the
        // CRC32 as eight upper-case hex digits. The client's own tier
        // reads several dialects (the CRC on the left, md5sum's `*`
        // marker, a quoted name); a generator emits the ordinary one,
        // and a row about a dialect is a key this plane does not have
        // yet rather than a second spelling smuggled in here.
        text.push_str(&format!("{} {:08X}\n", f.rel, h.finalize()));
    }
    Some(CompanionFile {
        name: profile.companion.sfv_file_name().to_string(),
        bytes: text.into_bytes(),
        names,
    })
}

#[cfg(test)]
mod tests {
    use crate::layout::generate;

    const BASE: &str = "\
[layout]
name = \"t\"
seed = 3

[source]
files = [{ name = \"one.flac\", bytes = 4096 }, { name = \"disc/two.flac\", bytes = 2048 }]

[encoding]
article_bytes = 4096
";

    fn built(extra: &str) -> crate::Layout {
        let p = crate::Profile::parse(&format!("{BASE}{extra}")).expect("profile parses");
        generate(&p).unwrap_or_else(|e| panic!("layout generates: {e}"))
    }

    fn sidecar(l: &crate::Layout) -> String {
        let (_, bytes) = l
            .files
            .iter()
            .find(|(n, _)| n.ends_with(".sfv"))
            .expect("the layout posts a sidecar");
        String::from_utf8(bytes.clone()).expect("the sidecar is text")
    }

    /// The neutral selection posts no sidecar at all.
    #[test]
    fn no_companion_is_the_neutral_row() {
        assert!(!built("").files.iter().any(|(n, _)| n.ends_with(".sfv")));
    }

    /// Every posted file gets a line, spelling its RELATIVE path - the
    /// tree is the thing an `.sfv` carries that a wire name cannot.
    #[test]
    fn the_sidecar_names_every_posted_file_by_its_relative_path() {
        let text = sidecar(&built("\n[companion]\nsfv = true\n"));
        assert!(text.contains("one.flac "), "{text}");
        assert!(text.contains("disc/two.flac "), "{text}");
        let lines = text.lines().filter(|l| !l.starts_with(';')).count();
        assert_eq!(lines, 2, "one line per posted file and no more: {text}");
    }

    /// ...and each checksum is that file's own, which is the only thing
    /// making the line a claim rather than a label.
    #[test]
    fn each_line_carries_that_files_crc32() {
        let l = built("\n[companion]\nsfv = true\n");
        let text = sidecar(&l);
        for (name, bytes) in l.files.iter().filter(|(n, _)| !n.ends_with(".sfv")) {
            let mut h = crc32fast::Hasher::new();
            h.update(bytes);
            let want = format!("{name} {:08X}", h.finalize());
            assert!(text.contains(&want), "missing {want:?} in:\n{text}");
        }
    }

    /// A member the post never carries gets no line: a checksum with no
    /// article behind it can be matched against nothing.
    #[test]
    fn a_described_but_unposted_member_gets_no_line() {
        let text = sidecar(&built(
            "\n[naming]\nwire = \"opaque\"\n\n[recovery]\nkind = \"par2\"\n\
             redundancy_pct = 10\nnames = \"filedesc-only\"\n\n[companion]\nsfv = true\n",
        ));
        // The layout above posts both payload files; add a dedupe copy
        // and the sidecar must still carry two lines.
        let with_copy = crate::Profile::parse(
            "[layout]\nname = \"t\"\nseed = 3\n\n[source]\nfiles = [\
             { name = \"one.flac\", bytes = 4096 }, \
             { name = \"two.flac\", bytes = 4096, same_as = \"one.flac\" }]\n\n\
             [naming]\nwire = \"opaque\"\n\n[recovery]\nkind = \"par2\"\nredundancy_pct = 10\n\
             names = \"filedesc-only\"\n\n[companion]\nsfv = true\n\n\
             [encoding]\narticle_bytes = 4096\n",
        )
        .expect("profile parses");
        let l = generate(&with_copy).expect("layout generates");
        let copy_text = sidecar(&l);
        assert!(
            !copy_text.contains("two.flac"),
            "the dedupe copy is on no wire, so it gets no line: {copy_text}"
        );
        assert!(text.contains("one.flac"), "{text}");
    }

    /// The sidecar is announced even when everything else is a token.
    #[test]
    fn the_sidecar_keeps_its_own_name_under_an_opaque_wire() {
        let l = built("\n[naming]\nwire = \"opaque\"\n\n[companion]\nsfv = true\n");
        assert!(
            l.files.iter().any(|(n, _)| n == "post.sfv"),
            "the sidecar is the one file that has to be findable: {:?}",
            l.files.iter().map(|(n, _)| n).collect::<Vec<_>>()
        );
        assert!(
            l.nzb.contains("post.sfv"),
            "and the map says so too, or nothing would ask for it"
        );
    }

    /// It draws nothing, so a row with a sidecar is a diff of the row
    /// without one.
    #[test]
    fn adding_a_sidecar_moves_no_payload_message_id() {
        let plain = built("\n[naming]\nwire = \"opaque\"\n");
        let with = built("\n[naming]\nwire = \"opaque\"\n\n[companion]\nsfv = true\n");
        let payload = |l: &crate::Layout| -> Vec<(String, Vec<u8>)> {
            l.files
                .iter()
                .filter(|(n, _)| !n.ends_with(".sfv"))
                .cloned()
                .collect()
        };
        assert_eq!(payload(&plain), payload(&with));
    }
}
