# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nzbfast.nzbfast
PackageVersion: 1.5.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-13
AppsAndFeaturesEntries:
- DisplayName: nzbfast
  Publisher: nzbfast
  ProductCode: '{72B5B673-54D7-46ED-BDDC-C7D3E571D242}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nzbfast/nzbfast/releases/download/v1.5.0/nzbfast-1.5.0-windows-x64-setup.exe
  InstallerSha256: E6DAA92B34E9C7323D86DC34A1A05EB12D03A124B2458C8ABF9B5A7001952FC0
ManifestType: installer
ManifestVersion: 1.12.0
