#!/usr/bin/env python3
"""Generate the mac app's Swift constants from the SHARED tables.

    apps/parfast/shared/strings/en.json   -> Sources/ParfastApp/Generated/Strings.swift
                                             Resources/Localizable.xcstrings
    apps/parfast/shared/design/tokens.json -> Sources/ParfastApp/Generated/Tokens.swift

Why a generator and not a hand-written Swift file: the two apps (chip B mac,
chip C Windows) must render the same palette and say the same words, and the
only way that survives a month of edits is ONE table with no second copy.
The Swift side is generated and COMMITTED so `swift build` works on a box
with no python and so a palette change is visible in the diff rather than
only in a build directory.

    ./Tools/generate.py            rewrite the generated files
    ./Tools/generate.py --check    fail if they are stale, or the copy rules
                                   are broken, or a colour has one theme only

--check is what a gate would run. It is deliberately NOT wired into
tools/preflight.py's roster: that roster is derived from size-gate.yml and
this tree is private (plan D2), so adding a workflow entry for it is chip D's
call, not this chip's. Run it by hand after editing either table.

COPY RULES CHECKED HERE (CLAUDE.md invariant 6, plan 5.7):
  - no em-dash (U+2014) or en-dash (U+2013) anywhere in a value
  - the word "streaming" never appears
  - a value may not start with a capital run that reads as Title Case for a
    button; that one is NOT machine-checkable, so it stays a review item and
    is named here rather than pretended about.

A colour token needs BOTH a light and a dark value. A single value is
refused rather than duplicated, because a palette that renders wrong in one
theme is the exact defect the dark blocks in the token file exist to stop.
"""

import argparse
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
MAC = HERE.parent
SHARED = MAC.parent / "shared"
STRINGS_JSON = SHARED / "strings" / "en.json"
TOKENS_JSON = SHARED / "design" / "tokens.json"
STRINGS_SWIFT = MAC / "Sources" / "ParfastApp" / "Generated" / "Strings.swift"
TOKENS_SWIFT = MAC / "Sources" / "ParfastApp" / "Generated" / "Tokens.swift"
XCSTRINGS = MAC / "Sources" / "ParfastApp" / "Resources" / "Localizable.xcstrings"

BANNED_CHARS = {"—": "em-dash", "–": "en-dash"}
BANNED_WORDS = ("streaming",)
PLACEHOLDER = re.compile(r"\{([a-z_][a-z0-9_]*)\}")
PLATFORM = "mac"

HEADER = (
    "// GENERATED by apps/parfast/mac/Tools/generate.py from\n"
    "// {src}\n"
    "// Do not edit this file. Edit the table and re-run the generator;\n"
    "// `Tools/generate.py --check` refuses a stale copy.\n"
)


def camel(key: str) -> str:
    parts = re.split(r"[._]", key)
    out = parts[0]
    for p in parts[1:]:
        out += p[:1].upper() + p[1:]
    return out


def swift_literal(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def resolve(strings: dict) -> tuple[dict, list[str]]:
    """Flatten platform splits down to this platform's copy.

    A value may be a string, or an object of platform keys. Five strings name
    a platform's own file manager or machine, and copy that is WRONG on the
    screen is worse than copy that is merely untranslated - so the split lives
    in the shared table rather than in an override layer each app maintains
    (chip C had to build one before this existed).

    A split that does not carry this platform's key is a REFUSAL, never a
    silent fallback to the other platform's wording: that is the shape this
    whole mechanism exists to prevent.
    """
    out, problems = {}, []
    for key, value in strings.items():
        if isinstance(value, str):
            out[key] = value
        elif isinstance(value, dict):
            if PLATFORM not in value:
                problems.append(
                    f"{key}: platform split carries {sorted(value)} and not {PLATFORM!r}")
                continue
            out[key] = value[PLATFORM]
        else:
            problems.append(f"{key}: value is neither a string nor a platform split")
    return out, problems


def check_copy(strings: dict) -> list[str]:
    problems = []
    for key, value in strings.items():
        for ch, name in BANNED_CHARS.items():
            if ch in value:
                problems.append(f"{key}: contains an {name}")
        low = value.lower()
        for word in BANNED_WORDS:
            if word in low:
                problems.append(f"{key}: contains the banned word {word!r}")
    return problems


def gen_strings(strings: dict) -> str:
    out = [HERE and HEADER.format(src="apps/parfast/shared/strings/en.json"), ""]
    out.append("import Foundation\n")
    out.append("/// Every user-facing word in the app. A value carrying {placeholders}")
    out.append("/// generates a function, so a missing argument is a compile error.")
    out.append("public enum S {")
    for key in sorted(strings):
        value = strings[key]
        names = []
        for m in PLACEHOLDER.finditer(value):
            if m.group(1) not in names:
                names.append(m.group(1))
        ident = camel(key)
        if not names:
            out.append(f"    /// {key}")
            out.append(f"    public static let {ident} = {swift_literal(value)}")
            continue
        args = ", ".join(f"{n}: String" for n in names)
        body = swift_literal(value)
        for n in names:
            body = body.replace("{" + n + "}", f"\\({n})")
        out.append(f"    /// {key}")
        out.append(f"    public static func {ident}({args}) -> String {{ {body} }}")
    out.append("}")
    return "\n".join(out) + "\n"


def parse_hex(value: str) -> tuple[float, float, float, float]:
    h = value.lstrip("#")
    if len(h) == 6:
        h += "FF"
    if len(h) != 8:
        raise ValueError(f"colour {value!r} is not #RRGGBB or #RRGGBBAA")
    r, g, b, a = (int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4, 6))
    return r, g, b, a


def colour_tokens(node, prefix, acc, problems):
    for name, value in node.items():
        if name.startswith("_"):
            continue
        if isinstance(value, dict) and "light" in value:
            if "dark" not in value:
                problems.append(f"colour {prefix}{name} has no dark value")
                continue
            acc.append((prefix + name, value["light"], value["dark"], value))
        elif isinstance(value, dict):
            colour_tokens(value, prefix + name + ".", acc, problems)


def gen_tokens(tokens: dict) -> tuple[str, list[str]]:
    problems: list[str] = []
    colours: list[tuple[str, str, str, dict]] = []
    colour_tokens(tokens["color"], "", colours, problems)

    lines = [HEADER.format(src="apps/parfast/shared/design/tokens.json"), ""]
    lines.append("import SwiftUI")
    lines.append("#if canImport(AppKit)")
    lines.append("import AppKit")
    lines.append("#endif\n")
    lines.append("/// The palette, spacing and motion constants, one source for both apps.")
    lines.append("public enum T {")
    lines.append("""
    /// A colour that follows the window's appearance. Resolved by AppKit so a
    /// Canvas, a shape and a Text all get the same answer in the same pass.
    static func dyn(_ light: (Double, Double, Double, Double),
                    _ dark: (Double, Double, Double, Double)) -> Color {
        #if canImport(AppKit)
        return Color(nsColor: NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            let c = isDark ? dark : light
            return NSColor(srgbRed: c.0, green: c.1, blue: c.2, alpha: c.3)
        })
        #else
        return Color(.sRGB, red: light.0, green: light.1, blue: light.2, opacity: light.3)
        #endif
    }
""")
    for path, light, dark, _meta in colours:
        lr, lg, lb, la = parse_hex(light)
        dr, dg, db, da = parse_hex(dark)
        lines.append(f"    /// {path}  light {light}  dark {dark}")
        lines.append(
            f"    public static let {camel(path)} = dyn("
            f"({lr:.4f}, {lg:.4f}, {lb:.4f}, {la:.4f}), "
            f"({dr:.4f}, {dg:.4f}, {db:.4f}, {da:.4f}))"
        )

    block = tokens["color"]["block"]
    ordered = sorted(
        ((v["code"], k, v["label"]) for k, v in block.items() if not k.startswith("_")),
    )
    lines.append("")
    lines.append("    /// Block states in `survey.block_runs` code order, so the map can index straight in.")
    lines.append("    public static let blockPalette: [Color] = [")
    for _code, name, _label in ordered:
        lines.append(f"        {camel('block.' + name)},")
    lines.append("    ]")
    lines.append("    public static let blockLabels: [String] = [")
    for _code, _name, label in ordered:
        lines.append(f"        {swift_literal(label)},")
    lines.append("    ]")

    for group, swift_type in (("spacing", "CGFloat"), ("radius", "CGFloat"), ("size", "CGFloat")):
        lines.append("")
        for name, value in tokens[group].items():
            if name.startswith("_"):
                continue
            lines.append(f"    public static let {camel(group + '.' + name)}: {swift_type} = {value}")
    lines.append("")
    for name, value in tokens["motion"].items():
        if name.startswith("_"):
            continue
        if isinstance(value, bool):
            lines.append(f"    public static let {camel('motion.' + name)} = {str(value).lower()}")
        else:
            lines.append(f"    public static let {camel('motion.' + name)}: Double = {value}")
    lines.append("}")
    return "\n".join(lines) + "\n", problems


def gen_xcstrings(strings: dict) -> str:
    catalog = {
        "sourceLanguage": "en",
        "strings": {
            key: {
                "extractionState": "manual",
                "localizations": {
                    "en": {"stringUnit": {"state": "translated", "value": value}}
                },
            }
            for key, value in sorted(strings.items())
        },
        "version": "1.0",
    }
    return json.dumps(catalog, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    raw = json.loads(STRINGS_JSON.read_text())["strings"]
    strings, problems = resolve(raw)
    tokens = json.loads(TOKENS_JSON.read_text())

    problems += check_copy(strings)
    tokens_swift, token_problems = gen_tokens(tokens)
    problems += token_problems
    strings_swift = gen_strings(strings)
    xcstrings = gen_xcstrings(strings)

    if problems:
        for p in problems:
            print(f"FAIL {p}", file=sys.stderr)
        return 1

    targets = [
        (STRINGS_SWIFT, strings_swift),
        (TOKENS_SWIFT, tokens_swift),
        (XCSTRINGS, xcstrings),
    ]
    stale = [p for p, text in targets if not p.exists() or p.read_text() != text]
    if args.check:
        if stale:
            for p in stale:
                print(f"FAIL stale: {p.relative_to(MAC.parent.parent.parent)}", file=sys.stderr)
            print("re-run apps/parfast/mac/Tools/generate.py", file=sys.stderr)
            return 1
        splits = sum(1 for v in raw.values() if isinstance(v, dict))
        print(f"ok: {len(strings)} strings ({splits} platform split), files current")
        return 0

    for path, text in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    splits = sum(1 for v in raw.values() if isinstance(v, dict))
    print(f"wrote {len(strings)} strings ({splits} platform split) "
          f"and {len(tokens['color'])} colour groups")
    return 0


if __name__ == "__main__":
    sys.exit(main())
